repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: local
    hooks:

    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]

    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]

    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
