name: Test

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.prod.yml up -d

      - name: Wait for services to be ready
        run: docker-compose -f docker-compose.prod.yml exec fastapi sh -c "while ! nc -z pgdb 5432; do sleep 1; done"

      - name: Run tests
        run: |
          docker-compose -f docker-compose.prod.yml exec fastapi pytest

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.prod.yml down
